import { router } from 'expo-router'; import * as ImagePicker from 'expo-image-picker'; import { useState } from 'react';
import { Alert, Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { colors, OnboardingShell, PrimaryButton, ui } from '../components/sjofn-ui'; import { supabase } from '../lib/supabase';
export default function OnboardingPhotosScreen() {
  const [imageUri, setImageUri] = useState<string | null>(null); const [mimeType, setMimeType] = useState('image/jpeg'); const [loading, setLoading] = useState(false);
  async function pickImage() { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { Alert.alert('Zugriff erforderlich', 'SJÖFN benötigt Zugriff auf deine Fotos, damit du ein Profilbild auswählen kannst.'); return; } const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsEditing: true, aspect: [1, 1], quality: 0.85 }); if (!result.canceled) { setImageUri(result.assets[0].uri); setMimeType(result.assets[0].mimeType ?? 'image/jpeg'); } }
  async function uploadPhoto() { if (!imageUri) { Alert.alert('SJÖFN', 'Bitte wähle zuerst ein Profilbild aus.'); return; } setLoading(true); try { const { data: { user }, error: userError } = await supabase.auth.getUser(); if (userError || !user) { Alert.alert('SJÖFN', 'Keine aktive Sitzung gefunden.'); return; } const response = await fetch(imageUri); const buffer = await response.arrayBuffer(); const extension = mimeType === 'image/png' ? 'png' : 'jpg'; const storagePath = `${user.id}/${Date.now()}.${extension}`; const { error: uploadError } = await supabase.storage.from('profile-photos').upload(storagePath, buffer, { contentType: mimeType, upsert: false }); if (uploadError) throw uploadError; const { error: databaseError } = await supabase.from('profile_photos').insert({ user_id: user.id, storage_path: storagePath, position: 0 }); if (databaseError) throw databaseError; const { error: profileError } = await supabase.from('profiles').update({ onboarding_step: 7 }).eq('id', user.id); if (profileError) throw profileError; router.push('/onboarding-complete'); } catch (error) { Alert.alert('Upload nicht möglich', error instanceof Error ? error.message : 'Unbekannter Fehler'); } finally { setLoading(false); } }
  return <OnboardingShell step={6} title="Zeig dich" accent="ganz echt." subtitle="Dein erstes Bild ist der Anfang deines Profils. Weitere Fotos kannst du später ergänzen." onBack={() => router.back()}>
    <Pressable style={styles.photoBox} onPress={pickImage} disabled={loading}>{imageUri ? <Image source={{ uri: imageUri }} style={styles.image} /> : <View style={styles.placeholder}><View style={styles.plusCircle}><Text style={styles.plus}>＋</Text></View><Text style={styles.placeholderTitle}>Hauptfoto hinzufügen</Text><Text style={ui.helper}>Tippe hier, um ein Bild auszuwählen</Text></View>}</Pressable>
    {imageUri && <Pressable onPress={pickImage} disabled={loading}><Text style={styles.change}>Anderes Bild wählen</Text></Pressable>}
    <PrimaryButton label="Weiter" loading={loading} disabled={!imageUri} onPress={uploadPhoto} /><Text style={ui.privacy}>Dein Foto wird geschützt gespeichert und kann später geändert werden.</Text>
  </OnboardingShell>;
}
const styles = StyleSheet.create({ photoBox: { width: '100%', aspectRatio: 1, maxHeight: 380, borderRadius: 26, overflow: 'hidden', borderWidth: 1, borderStyle: 'dashed', borderColor: '#DFC8C3', backgroundColor: '#FFF2F3' }, image: { width: '100%', height: '100%' }, placeholder: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 20 }, plusCircle: { width: 62, height: 62, borderRadius: 31, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.white, marginBottom: 14 }, plus: { color: colors.rose, fontSize: 34 }, placeholderTitle: { color: colors.ink, fontSize: 17, fontWeight: '800', marginBottom: 5 }, change: { color: colors.rose, textAlign: 'center', fontWeight: '700', paddingVertical: 14 } });
